version: '3.3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    networks:
      - proxy
    ports:
      - '80:80'
      - '443:443'
    environment:
      - ENABLE_IPV6=true
      - DEFAULT_HOST=bloggrammer.com, www.bloggrammer.com
      # - DHPARAM_GENERATION=false
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./dhparam:/etc/nginx/dhparam
      - ./html:/usr/share/nginx/html
      - ./vhost:/etc/nginx/vhost.d

volumes:
  conf:
  vhost:
  dhparam:
  certs:
  html:

networks:
  proxy:
    external: true
